### ISSUE TITLE
100M＋ Memory  saver反馈

### ISSUE THREAD

**Issue by naloder** [llikz/app2vr#2]
节省效果的确看出来了，不过开机后图片大小变小了，显示有问题

**Comment by llikz** [comment]
new version fixed this bug

**Comment by sw1313** [comment]
LG g5的息屏显示图片会损坏
always on display of LG g5 is broken.

**Comment by llikz** [comment]
收到 能否提供一下log




发自网易邮箱大师
在2017年05月16日 08:46，sw1313 写道：

LG g5的息屏显示图片会损坏
always on display of LG g5 is broken.

**Comment by naloder** [comment]
新版图片大小bug修复之后，又一bug出现，图片清晰度受到影响

_Sent from my Meizu M3s using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yugeigei** [comment]
miui使用后   部分软件的图标被异常放大，看着特别扭
